### PR TITLE
Add ability to disable -b:v

### PR DESCRIPTION
**Pull request by marbocub**
Fix https://github.com/protonemedia/laravel-ffmpeg/issues/299

### CODE REVIEW

**Comment by pascalbaljet** [comment]
I'll leave this one opened until a new version of the underlying library is tagged.

**Comment by Romain** [comment]
I'm gonna release a new version of [PHP-FFMPEG](https://github.com/PHP-FFMpeg/PHP-FFMpeg) so you'll be able to get rid off this change.

**Comment by Romain** [comment]
v0.18.0 has just been published.

**Comment by pascalbaljet** [comment]
Thanks @Romain!

**Comment by Romain** [comment]
You're welcome.

**Pull request merged**
